version: '3.2'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9000:9000"
    volumes:
      - /Users/zhizhu/www:/data/www:rw #资源目录，需更改为自己的项目目录
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm
    extra_hosts:
        #host
        - "master.mysql.com:127.0.0.1"
        - "caipiao.mysql.com:192.168.0.101"
  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - /Users/zhizhu/www:/data/www:rw #资源目录，需更改为自己的项目目录
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'
